spring.application.name=pymes_web_backend_springboot
spring.datasource.url=jdbc:mysql://localhost:3306/pymes_db
spring.datasource.username=root
spring.datasource.password=Copernico420@\#
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
# Dejar que Spring detecte el dialecto automáticamente (evita ClassNotFound)
spring.jpa.show-sql=true
# Para desarrollo: que Hibernate cree/actualice tablas automáticamente.
# En producción usa migraciones (Flyway/Liquibase) y elimina esta propiedad.
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.jpa.hibernate.ddl-auto=none
logging.level.org.flywaydb=DEBUG
